{
  "uid" : "823043a6b79a09",
  "name" : "test_sub[0--999999999999999-999999999999999]",
  "fullName" : "test_calc.TestCalc#test_sub",
  "historyId" : "3b2d2c6b28c66259e592b0a32051cfec",
  "time" : {
    "start" : 1612147341768,
    "stop" : 1612147341769,
    "duration" : 1
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: assert False",
  "statusTrace" : "self = <testcase.test_calc.TestCalc object at 0x0000023BC1279E20>, a = 0, b = -999999999999999, expect = 999999999999999\nget_calc = <test_code.calc.Calculator object at 0x0000023BC1308670>\n\n    @pytest.mark.parametrize(\"a,b,expect\", subdatas_data)\n    @pytest.mark.run(order=2)\n    def test_sub(self, a, b, expect,get_calc):\n    \n        if isinstance(a, str):\n            print(\"非数字类型\")\n            assert False\n    \n        elif a is None:\n            print(\"不能为空\")\n            assert False\n    \n        elif 999999 <= b or b <= -999999:\n            print(\"超出最大值\")\n>           assert False\nE           assert False\n\ntest_calc.py:113: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "get_calc",
    "time" : {
      "start" : 1612147341617,
      "stop" : 1612147341617,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "AssertionError: assert False",
    "statusTrace" : "self = <testcase.test_calc.TestCalc object at 0x0000023BC1279E20>, a = 0, b = -999999999999999, expect = 999999999999999\nget_calc = <test_code.calc.Calculator object at 0x0000023BC1308670>\n\n    @pytest.mark.parametrize(\"a,b,expect\", subdatas_data)\n    @pytest.mark.run(order=2)\n    def test_sub(self, a, b, expect,get_calc):\n    \n        if isinstance(a, str):\n            print(\"非数字类型\")\n            assert False\n    \n        elif a is None:\n            print(\"不能为空\")\n            assert False\n    \n        elif 999999 <= b or b <= -999999:\n            print(\"超出最大值\")\n>           assert False\nE           assert False\n\ntest_calc.py:113: AssertionError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "74362b6d6f9c626a",
      "name" : "stdout",
      "source" : "74362b6d6f9c626a.txt",
      "type" : "text/plain",
      "size" : 16
    } ],
    "parameters" : [ ],
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : true,
    "stepsCount" : 0,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "tag",
    "value" : "run(order=2)"
  }, {
    "name" : "suite",
    "value" : "test_calc"
  }, {
    "name" : "subSuite",
    "value" : "TestCalc"
  }, {
    "name" : "host",
    "value" : "LAPTOP-CV4D84I5"
  }, {
    "name" : "thread",
    "value" : "32636-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_calc"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "a",
    "value" : "0"
  }, {
    "name" : "b",
    "value" : "-999999999999999"
  }, {
    "name" : "expect",
    "value" : "999999999999999"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "run(order=2)" ]
  },
  "source" : "823043a6b79a09.json",
  "parameterValues" : [ "0", "-999999999999999", "999999999999999" ]
}