{"name": "test_div[nonefail]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <testcase.test_calc.TestCalc object at 0x0000023BC13D1D30>, a = None, b = 5, expect = 5, get_calc = <test_code.calc.Calculator object at 0x0000023BC1308670>, caculate = None\n\n    @pytest.mark.parametrize(\"a,b,expect\", divdatas_data, ids=myid_div)\n    @pytest.mark.run(order=4)\n    def test_div(self, a, b, expect,get_calc,caculate):\n        # 判断b不能等于0\n        if b == 0:\n            print(\"除数不能等于0\")\n            assert False\n    \n        elif a is None:\n            print(\"不能为空\")\n>           assert False\nE           assert False\n\ntest_calc.py:85: AssertionError"}, "attachments": [{"name": "stdout", "source": "107a8f12-dc1c-4620-8f28-c39c3fda2576-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "None"}, {"name": "b", "value": "5"}, {"name": "expect", "value": "5"}], "start": 1612147341907, "stop": 1612147341907, "uuid": "6586424b-c9ae-4893-834c-10293a00a50a", "historyId": "98a49ebdaa9588e61d11f802fefb0726", "testCaseId": "4a57f615ae930c12d705a9fc7a66b88d", "fullName": "test_calc.TestCalc#test_div", "labels": [{"name": "tag", "value": "run(order=4)"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "LAPTOP-CV4D84I5"}, {"name": "thread", "value": "32636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}