{"name": "test_mul[999999999999-1-999999999999]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <testcase.test_calc.TestCalc object at 0x0000023BC139F3D0>, a = 999999999999, b = 1, expect = 999999999999, get_calc = <test_code.calc.Calculator object at 0x0000023BC1308670>\ncaculate = None\n\n    @pytest.mark.parametrize(\"a,b,expect\", muldatas_data)\n    @pytest.mark.run(order=3)\n    def test_mul(self, a, b, expect,get_calc,caculate):\n        if isinstance(a, str):\n            print(\"非数字类型\")\n            assert False\n    \n        elif a is None:\n            print(\"不能为空\")\n            assert False\n    \n        elif 999999 <= a or a <= -999999:\n            print(\"超出最大值\")\n>           assert False\nE           assert False\n\ntest_calc.py:138: AssertionError"}, "attachments": [{"name": "stdout", "source": "e3d0597f-c18f-4de1-963a-51660eb3c695-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "999999999999"}, {"name": "b", "value": "1"}, {"name": "expect", "value": "999999999999"}], "start": 1612147341840, "stop": 1612147341841, "uuid": "ca8fce72-72e9-477e-b0fc-df6fb0f462dc", "historyId": "22c6e13c61b48fc1027bb685f8c3cd99", "testCaseId": "463eb02829151a13063664521f3c4534", "fullName": "test_calc.TestCalc#test_mul", "labels": [{"name": "tag", "value": "run(order=3)"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "LAPTOP-CV4D84I5"}, {"name": "thread", "value": "32636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}